# Site settings
title: Sumner Web Design - A portfolio site
email: shred1162@gmail.com
description: A portfolio site with work examples and collection of resources.
url: "#" # the base hostname & protocol for your site
#twitter_username: guilh
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Ted Sumner
      layout: "post"
      category: sites
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
